### ISSUE TITLE
Emcdns=1 activates Emercoin DNS server only on port ipv6

### ISSUE THREAD

**Issue by lavaed** [emercoin/emercoin#100]
**Expected behavior**

**Actual behavior**

**To reproduce**

**System information**

Emercoind 0.7.10 installed on ubuntu 18.05 kernel 5.2

**Comment by maxihatop** [comment]
EmerDNS uses dual port, both v4/v6
For example, see output:

FreeBSD:
root@bsd# sockstat -l | grep emer
olegh    emercoind  69482 25 udp46  *:5335                *:*

Unfortunately, Linux does not show ipv4 connection for dual port, but it works OK:
CentOS:
# lsof -i -P -n | grep emer | grep -i udp
emercoind 18698      emc   30u  IPv6 1399235436      0t0  UDP *:53 

# dig +short emer.coin @127.0.0.1
104.238.236.163

**Comment by lavaed** [comment]
What's most interesting is that I have disabled ipv6 in ubuntu, and when I run EmerDNS, only udp6 :: 5335 appears in netstat output.

**Comment by maxihatop** [comment]
I think, Linux incorrectly shows the dual protocol "46" as "6".
