### ISSUE TITLE
MacOS version emercoin-qt is not working

### ISSUE THREAD

**Issue by bitcoren** [emercoin/emercoin#109]
MacOS version emercoin-qt is not working v0.7.11-1 arm and amd64:
```
bitcoren@MacMini ~ % /Users/bitcoren/Downloads/pkg/usr/bin/emercoin-qt
dyld[20734]: Library not loaded: /opt/local/libexec/boost/1.76/lib/libboost_filesystem-mt.dylib
  Referenced from: /Users/bitcoren/Downloads/pkg/usr/bin/emercoin-qt
  Reason: tried: '/opt/local/libexec/boost/1.76/lib/libboost_filesystem-mt.dylib' (no such file), '/usr/local/lib/libboost_filesystem-mt.dylib' (no such file), '/usr/lib/libboost_filesystem-mt.dylib' (no such file)
zsh: abort      /Users/bitcoren/Downloads/pkg/usr/bin/emercoin-qt
```

**Comment by maxihatop** [comment]
Sorry, we do not support MAC version anymore for 0.7.X

**Comment by ebretteville** [comment]
@maxihatop So we need to use a VM or something running linux? Anyway we can compile for macos?

**Comment by maxihatop** [comment]
Sorry, since 0.7.11 we do not support MACOS build.
We do not have environmant or Apple dev credentials, to create such builds.
However, if someone, who works with MACOS and have such dev-credentials will build - we're welcome to accept his contribution.
