### ISSUE TITLE
Own EmerDNS resolver

### ISSUE THREAD

**Issue by sergeysedoy97** [emercoin/emercoin#110]
**Is your feature request related to a problem? Please describe.**
For now to access to EmerDNS zones we need to use browser extensions or OpenNIC.

**Describe the solution you'd like**
Would like to have ability to setup own DNS resolver.

**Comment by maxihatop** [comment]
See the article: https://emercoin.com/en/documentation/blockchain-services/emerdns/emerdns-introduction/
Chapters:
https://emercoin.com/en/documentation/blockchain-services/emerdns/emerdns-introduction/#access
https://emercoin.com/en/documentation/blockchain-services/emerdns/emerdns-introduction/#integration
To setup local resolver, you need to run any standard DNS server, libe BINS, Unbound, DNSMASQ or so on, and forward Emer zones to localhost:5335 (if you run emer-node on the same server).

**Comment by sergeysedoy97** [comment]
Thank You.
