### ISSUE TITLE
v6 warning.

### ISSUE THREAD

**Issue by p3yot3** [Emercoin/emercoin#26]
"version": 60000,
  "protocolversion": 70002,
  "walletversion": 60000,
  "blocks": 214384,

"errors": "**WARNING: Checkpoint is too old. Wait for block chain to download, or notify developers of the issue**."

**Comment by snvakula** [comment]
It's a normal operation. Blockchain should be re-indexed since v0.6.0.

**Comment by p3yot3** [comment]
It's not normal at all & the blockchain was reindexed.
