### ISSUE TITLE
[FR] pre-packaged wallet

### ISSUE THREAD

**Issue by osmoc** [emercoin/emercoin#29]
Would be great to get not only wallet's source code but also pre-build binaries for GNU/Linux. Personally I'm interested in .deb but I imagine others would love to .rpm and so on. This would greatly help to decrease entry barrier for new users while ensuring that all the clients use latest updates available. Ideally it should be included into major GNU/Linux distributions like Ubuntu/Debian, Fedora/RHEL etc, but for starter ppa (for .deb) and copr (for .rpm) would be great already.

**Comment by snvakula** [comment]
Please refer to https://emercoin.com/#download for linux packages
