### ISSUE TITLE
networkhashps returns zero?

### ISSUE THREAD

**Issue by vx28643** [emercoin/emercoin#32]
Hello, 

I am trying to get network hashrate for statistics page however:

Command ```emc getmininginfo``` returns ```"networkhashps": 0```
Also help command  ```emc help getmininginfo``` does not include descriptor for networkhashps

How can I retrieve total network hashes statistic?

Thank you.

**Comment by EvgenijM86** [comment]
I will fix this in 0.7.0emc. Currently you can calculate this by using block difficulty:

tmp = difficulty  (2^32) / (3600  24 / pow_blocks_per_day);
hashrate = tmp / 1e+15; // to petahash/s
