### ISSUE TITLE
The package is not installed

### ISSUE THREAD

**Issue by vladns** [emercoin/emercoin#33]
The package is not installed:

root@ubuntu:~# apt-key adv --keyserver keyserver.ubuntu.com --recv B58C58F4
Executing: /tmp/tmp.nKxXrbZlWR/gpg.1.sh --keyserver
keyserver.ubuntu.com
--recv
B58C58F4
gpg: запрашиваю ключ B58C58F4 с сервера hkp keyserver.ubuntu.com
gpg: ключ B58C58F4: импортирован открытый ключ "Aspanta Limited <info@aspanta.com>"
gpg: Всего обработано: 1
gpg:               импортировано: 1  (RSA: 1)
root@ubuntu:~# add-apt-repository 'deb http://download.emercoin.com/ubuntu xenial emercoin'
root@ubuntu:~# apt update && apt -y install emercoin
Игн:1 http://download.emercoin.com/ubuntu xenial InRelease
Пол:2 http://ru.archive.ubuntu.com/ubuntu xenial InRelease [247 kB]
Сущ:3 http://security.ubuntu.com/ubuntu xenial-security InRelease
Ошк:4 http://download.emercoin.com/ubuntu xenial Release
  **403  Forbidden [IP: 2400:cb00:2048:1::6818:7fab 80]**
Пол:5 http://ru.archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]
Пол:6 http://ru.archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]
Чтение списков пакетов… Готово
E: Репозиторий «http://download.emercoin.com/ubuntu xenial Release» не содержит файла Release.
N: Обновление из этого репозитория нельзя выполнить безопасным способом, и поэтому по умолчанию он отключён.
N: Смотрите справочную страницу apt-secure(8) о создании репозитория и настройке пользователя.

**Comment by snvakula** [comment]
Пожалуйста, попробуйте снова.
Проблемы сегодня быть не должно.
