### ISSUE TITLE
The private key cannot be imported into system

### ISSUE THREAD

**Issue by tadas-subonis** [emercoin/emercoin#34]
Hi, 

I have created a private key with https://walletgenerator.net/

Now I am trying to do
```
./emercoin-cli importprivkey SomePrivateKey
```
and it says

```
error code: -5
error message:
Invalid private key encoding
```

What's the problem? It doesn't work on win64 and linux64.

**Comment by tadas-subonis** [comment]
Apparently, you need to use an old client.

It can be found here http://olegh.ftp.sh/emercoin-0.3.7-windows.7z

**Comment by vx28643** [comment]
Did that solution work for you? I know that the issue has already been reported to walletgenerator [here](https://github.com/MichaelMure/WalletGenerator.net/issues/48).

**Comment by tadas-subonis** [comment]
It helped. I had to import the key with version 0.3.7, and then I was able to sync with the network with the newest version
