### ISSUE TITLE
Recent transactions in overview not updating

### ISSUE THREAD

**Issue by Maetiz** [emercoin/emercoin#38]
The list of transactions shown on the overview tab is missing latest transactions that can be found in the transactions tab. The transactions where the overview is "stuck" in are PoS transactions that were not accepted.
![image](https://user-images.githubusercontent.com/3485256/29729435-ca338980-89e4-11e7-84bd-889ae954c695.png)
![image](https://user-images.githubusercontent.com/3485256/29729455-dee11186-89e4-11e7-9009-b5928fcc72f6.png)

**Comment by EvgenijM86** [comment]
I will automatically remove unconfirmed PoS in next version (0.7.0).
