### ISSUE TITLE
Web translation Spanish

### ISSUE THREAD

**Issue by miansegat** [emercoin/emercoin#40]
Spanish is one of the most spoken languages ​​in the world. This would allow greater access to information and increase the dissemination and participation.

**Comment by PanderMusubi** [comment]
Setup up translation via a free service such as Weblate, see https://hosted.weblate.org/about/ on how to register. This will make adding translations very easy and open up Emercoin to a wider audience as @miansegat says.

**Comment by PanderMusubi** [comment]
Another service to use is Transifex, see for example how Dash does their translation at https://www.transifex.com/dash/dash-website/dashboard/

**Comment by EvgenijM86** [comment]
You can submit pull requests for translation if you want.

**Comment by PanderMusubi** [comment]
@EvgenijM86 in which repo is the website?
