### ISSUE TITLE
Compile with static libraries

### ISSUE THREAD

**Issue by compilenewbe** [emercoin/emercoin#45]
i want to compile emercoin with statics libraries, and everytime i compile it and move it to another computer, i have an error message saying 

error while loading shared libraries: libboost_program_options.so.1.58.0: cannot open shared object file: No such file or directory.

Can someone help me please.

**Comment by EvgenijM86** [comment]
If you are compiling with "make" it will dynamically link to libboost version that is available on your systen. If target machine has a different version of libboost it will not work. You can fix this by installing libboost 1.58 on the machine that you moved your wallet. Or you can gitian builder script on virtual machine to compile statically linked binary.
