### ISSUE TITLE
Three year old wallet no longer works     

### ISSUE THREAD

**Issue by stwbitcoin** [emercoin/emercoin#46]
I have not touched my Emercoin wallet in over three years. It works but is 3years 10 weeks behind. After two hours blocks are downloading but it is still 3 years 10 weeks behind. 

Tried installing a new wallet but when I start it I get this error: 
![image](https://user-images.githubusercontent.com/29934581/33234755-be2f0878-d1e0-11e7-80d5-c1f48676a1fe.png)
I get the same error on both 64 and 32bit windows installs.
Since I don't see the image I am trying to upload; it says EXCEPTION: St13runtime_error   CDB: Error -30974, can't open database   C:ProgramFiles (x86)\Emercoin\emercoin-qu.exe in Runaway exception

I have no idea what that means. Can anyone help?

FYI: My idea was to install the new wallet and then move the wallet.dat file into the new location. My original wallet dat file is on a NAS backup not connected to this machine.

I can be reached at stwbitcoin@1ids.com 

I would appreciate any help I can get.

**Comment by stwbitcoin** [comment]
IS ANYONE THERE? It has been three days!

**Comment by warmach** [comment]
Try deleting everything, except wallet file, and then letting old app recreate it all and re-downloading block chain
