### ISSUE TITLE
inconsistent name_new function documentation

### ISSUE THREAD

**Issue by kolinsol** [emercoin/emercoin#54]
emercoin cli provides inconsistent API documentation for name_new function

This is a part of cli output for 'emc name_new help' command

ame_new (name) (value) (days) [toaddress] [valuetype]
Creates new key->value pair which expires after specified number of days.
Cost is square root of (1% of last PoW + 1% per year of last PoW).
Arguments:
1. name (string, required) Name to create.
2. value (string, required) Value to write.
3. toaddress (string, optional) Address of recipient. Empty string = transaction to yourself.
4. valuetype (string, optional) Interpretation of value string. Can be "hex", "base64" or filepath.

(days) parameter is not mentioned in the arguments list but mentioned in the listing of the function

**Comment by EvgenijM86** [comment]
fixed in version 7
