### ISSUE TITLE
missing bits in getauxblock

### ISSUE THREAD

**Issue by djayr** [emercoin/emercoin#64]
Getauxblock output for Emercoin is like

{
  "target": "000000000000000000000000000000000000000025f517000000000000000000",
  "hash": "947430409f2735a557b918f219b19567d339a4fcd4c93ef9e463b787fc52ba31",
  "chainid": 666
}

Look how it's for namecoin

{
  "hash": "574f20c7b2b1f810e9d7adf5b72af031112fc51bd770608b6bafd694b3efa0c7",
  "chainid": 1,
  "previousblockhash": "0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206",
  "coinbasevalue": 5000000000,
  "bits": "207fffff",
  "height": 1,
  "_target": "0000000000000000000000000000000000000000000000000000000000ffff7f"
}

[nBits field in bitcoin block header] (https://bitcoin.org/en/developer-reference#target-nbits)

Can you please add "bits" in getauxblock output ?

**Comment by EvgenijM86** [comment]
Ok, I will add it in the next minor release.

**Comment by EvgenijM86** [comment]
added
