### ISSUE TITLE
Offer binaries also on GitHub

### ISSUE THREAD

**Issue by PanderMusubi** [emercoin/emercoin#65]
Please, also offer the binaries on SourceForge at https://sourceforge.net/projects/emercoin/files/0.7.0/ also on GitHub at https://github.com/emercoin/emercoin/releases/tag/v0.7.0emc

Lots of users will navigate from the Emercoin website download page https://emercoin.com/en/benefits#download to GitHub, finding only source files, which can be discouraging and result that person does not install Emercoin wallet.

**Comment by EvgenijM86** [comment]
done

**Comment by PanderMusubi** [comment]
Thanks
