### ISSUE TITLE
used newer master keep bug. cannot used GUI just console[tiresome]

### ISSUE THREAD

**Issue by FndNur1Labs** [emercoin/emercoin#68]
This issue tracker is only for technical issues related to bitcoin-core.

General bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

For reporting security issues, please read instructions at [https://bitcoincore.org/en/contact/](https://bitcoincore.org/en/contact/).

### Describe the issue
qt/gui.h:14:18: fatal error: QLabel: No such file or directory
 #include <QLabel>

### Screenshots.
![image](https://user-images.githubusercontent.com/11433397/44027909-2a1eaa8c-9f33-11e8-9a6b-266a7d838cd6.png)

### What version of emer-core are you using?
0.7.0

### Machine specs:
- OS: Debian 9.5
- CPU: I7-Extreme
- RAM: 64GB
- Disk size: 2Tb
- Disk Type (HD/SDD): SDD

**Comment by FndNur1Labs** [comment]
@EvgenijM86 even used high spec same?strange...

**Comment by EvgenijM86** [comment]
We don't have this file - src/qt/gui.h - in 0.7.0. Can't fix files that I don't have.

**Comment by FndNur1Labs** [comment]
ah that bitcoingui.h. i made simple script for make self. no worries ahaha.

https://github.com/emercoin/emercoin/blob/master/src/qt/bitcoingui.h

try it on debian not work.

**Comment by EvgenijM86** [comment]
Can't reproduce error. Here is what I did on my Debian 9 virtual machine:
git pull
make clean
make

```
  CXX      qt/qt_libbitcoinqt_a-qrc_bitcoin_locale.o
  AR       libbitcoin_server.a
/usr/bin/ar: `u' modifier ignored since `D' is the default (see `U')
  CXXLD    emercoin-cli
  CXXLD    emercoin-tx
  CXXLD    emercoind
  CXXLD    bench/bench_bitcoin
  AR       qt/libbitcoinqt.a
/usr/bin/ar: `u' modifier ignored since `D' is the default (see `U')
/usr/bin/ld: warning: libssl.so.1.1, needed by /usr/local/lib/libevent_openssl.so, may conflict with libssl.so.1.0.2
/usr/bin/ld: warning: libcrypto.so.1.1, needed by /usr/local/lib/libevent_openssl.so, may conflict with libcrypto.so.1.0.2
/usr/bin/ld: warning: libssl.so.1.1, needed by /usr/local/lib/libevent_openssl.so, may conflict with libssl.so.1.0.2
/usr/bin/ld: warning: libcrypto.so.1.1, needed by /usr/local/lib/libevent_openssl.so, may conflict with libcrypto.so.1.0.2
  OBJCXXLD qt/emercoin-qt
/usr/bin/ld: warning: libssl.so.1.1, needed by /usr/local/lib/libevent_openssl.so, may conflict with libssl.so.1.0.2
/usr/bin/ld: warning: libcrypto.so.1.1, needed by /usr/local/lib/libevent_openssl.so, may conflict with libcrypto.so.1.0.2
make[2]: Leaving directory '/home/evgenij/programming/emercoin/src'
make[1]: Leaving directory '/home/evgenij/programming/emercoin/src'
Making all in doc/man
make[1]: Entering directory '/home/evgenij/programming/emercoin/doc/man'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/evgenij/programming/emercoin/doc/man'
make[1]: Entering directory '/home/evgenij/programming/emercoin'
make[1]: Nothing to be done for 'all-am'.
make[1]: Leaving directory '/home/evgenij/programming/emercoin'
```

**Comment by EvgenijM86** [comment]
And emercoin-qt also builds on my debian 9. I did not change anything on that VM, other than doing git pull and rebuilding. So instructions on how to build should be the same as posted here: https://github.com/emercoin/emercoin/issues/63#issuecomment-409631093

btw, your error indicates that for some reason build script do not see QT installation.

**Comment by FndNur1Labs** [comment]
already try same with my friend. we missing something maybe~i will tell again later. after work

**Comment by FndNur1Labs** [comment]
fixed
