### ISSUE TITLE
emercoin v0.7.1 not available from apt repository

### ISSUE THREAD

**Issue by Maetiz** [emercoin/emercoin#69]
The Ubuntu apt repository download.emercoin.com (documented here: https://emercoin.com/en/documentation/install-software/core-wallets/cli-daemon) does not have the newest version (https://github.com/emercoin/emercoin/releases/tag/v0.7.1emc) available.

Sorry if this is the wrong place to report the issue, but I couldn't figure out where else to report this.

**Comment by EvgenijM86** [comment]
I have sent notification to whoever is responsible for apt packages.

**Comment by EvgenijM86** [comment]
I have asked that person directly and he said that they soon will be available.

**Comment by prudnitskiy** [comment]
0.7.2 is also not available from repository...

**Comment by EvgenijM86** [comment]
Yes, I have notified the guy who made those packages and he does not respond for some reason. I'm not sure what is going on there. We might drop support for those packages if he does not respond soon (until we find someone else to do it). For now you can use tar.gz version with compiled binaries - https://github.com/emercoin/emercoin/releases

**Comment by mechnotech** [comment]
There are old tutirial that still working: 
https://translate.google.ru/translate?hl=&sl=ru&tl=en&u=https%3A%2F%2Fcryptor.net%2Ftutorial%2Fustanovka-emercoind-na-vps
Sorry, GoogleTranslate from russian.
