### ISSUE TITLE
0.7.1 crashes when disablewallet = 1

### ISSUE THREAD

**Issue by Kimax89** [emercoin/emercoin#70]
1. `disablewallet=1` in the emercoin.conf
2. Start up the client.
3. when it initiate network threads. the client crashes.

I would like to run the Emercoin as a Full Node with GUI and not as a wallet.

- OS: Windows Server 2016
- CPU: Xeon E5430 2.66GHz 64-bit
- RAM: 40GB DDR2
- Disk size: 1500GB
- Disk Type: 7200 RPM HDD

I try'd launching the client with only `disablewallet=1` in it and it still crashes.

**Comment by EvgenijM86** [comment]
Yes, we did not write emercoin code without wallet support yet - I forgot to remove that option. For now you can just run it with empty wallet.

Is this feature needed? What exactly do you gain vs empty wallet?

**Comment by Kimax89** [comment]
I'm one of the biggest host of Full Nodes in Denmark and i do this to strengthen the networks.
I currently have 8 nodes running and Emercoin would be my 9th.

I got my own hosting location with a tier 1 ISP and have extremely low latency to all around scandinavia and europe and therefore i can be beneficial for securing the networks integrity and a low latency for distribution of transactions and new blocks.

**Comment by Kimax89** [comment]
i disable the wallet because i dont want to look at an empty wallet and have to open the debug windows each time i wanna check the status.

I like to run it as a node only and only have the debug window to look at.

**Comment by EvgenijM86** [comment]
Ok, I will see if I can refactor the code to allow this option.

**Comment by EvgenijM86** [comment]
I think I have just fixed that in master.

**Comment by Kimax89** [comment]
If your able to build a Win64, it would be great and i would be able to launch it, right away.

**Comment by EvgenijM86** [comment]
I uploaded builds here:
https://sourceforge.net/projects/emercoin/files/other%20builds/0.7.1-disablewallet-fix/

Let me know if they fixed your issue.

**Comment by EvgenijM86** [comment]
And what exactly is happening. Does it crash like before?

**Comment by EvgenijM86** [comment]
I have removed those builds and I have uploaded a fix to the same link - https://sourceforge.net/projects/emercoin/files/other%20builds/0.7.1-disablewallet-fix/ . I have tested it on empty emercoin.conf (only with disablewallet=1) on windows and it appears to work:

![disablewallet](https://user-images.githubusercontent.com/430076/45681917-69637d00-bb47-11e8-9592-b69b08a2756b.png)

**Comment by Kimax89** [comment]
I can now confirm that the fix you made is working.

I'm now running a Fully Synced Emercoin Node with the wallet disabled.
