### ISSUE TITLE
BTC вместо EMC

### ISSUE THREAD

**Issue by grumbler66rus** [Emercoin/emercoin#8]
Всё ещё не убрано название биткоина (BTC, mBTC, μBTC) из правого нижнего угла. Причём при клике по надписи показывается меню с правильными строками (EMC, mEMC, μEMC).

![emc-btc](https://cloud.githubusercontent.com/assets/15853954/15956113/0a07a98a-2f08-11e6-8328-09d36b7743de.png)
![emercoin-btc](https://cloud.githubusercontent.com/assets/15853954/15956095/ec05a8ec-2f07-11e6-99c5-4776f9ae22b5.png)

Виноваты картинки 
src/qt/res/icons/unit_btc.png
src/qt/res/icons/unit_mbtc.png
src/qt/res/icons/unit_ubtc.png

**Comment by EvgenijM86** [comment]
Я это уже исправил в новом клиенте.
