### ISSUE TITLE
Build fails in multiple places if configured with "--disable-wallet"

### ISSUE THREAD

**Issue by h0m3us3r** [emercoin/emercoin#81]
Main offender so far is "MapRandKeyT" which is referenced in many places outside of #ifdef ENABLE_WALLET and is undefined if wallet.h is not included (and it is only included inside #ifdef ENABLE_WALLET).

**Comment by EvgenijM86** [comment]
Yes, we never supported that option. You can use disablewallet=1 in emercoin.conf if you wish and it should work. I am not sure if we will fix it or not. Going to discuss this with our team.
