### ISSUE TITLE
Emercoin-Qt compiled from source does not start

### ISSUE THREAD

**Issue by lockedshadow** [emercoin/emercoin#82]
Emercoin-Qt compiled from source code using [this PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=emercoin) does not start with no output to both console and debug.log, while emercoind compiled using the same method behaves correctly. Official binary release of Emercoin-Qt also behaves correctly. Passing `-debug=qt`  to the command line options has no visible effect.

Distro: ArchLinux
Qt version: 5.11.2
Boost version: 1.68.0

**Comment by EvgenijM86** [comment]
Yes, we never supported that option. You can use disablewallet=1 in emercoin.conf if you wish. I am not sure if we will fix it or not. Going to discuss this with our team.

**Comment by EvgenijM86** [comment]
Can't reproduce this on ubuntu-16.04 with those configuration options - emercoin-qt runs without problem on that distro. I will install ArchLinux on a virtual machine sometimes this week to try to reproduce this.

**Comment by lockedshadow** [comment]
Maybe there is also a way to provide you more detailed debug information?

**Comment by EvgenijM86** [comment]
I am not sure how. If debug.log is not created it means it crashed very early, before even loading anything related to crypto itself.

**Comment by lockedshadow** [comment]
Well, I've compile it with `--enable-debug`, and after tracing with gdb, I got following...

```
(gdb) run
Starting program: /usr/bin/emercoin-qt
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff00e9700 (LWP 4745)]
[New Thread 0x7fffecf09700 (LWP 4746)]
^C
Thread 1 "emercoin-qt" received signal SIGINT, Interrupt.
0x00007ffff56054ed in syscall () from /usr/lib/libc.so.6
(gdb) where
#0  0x00007ffff56054ed in syscall () from /usr/lib/libc.so.6
#1  0x00007ffff59252e1 in __cxxabiv1::__cxa_guard_acquire (g=0x7ffff7bfd660) at /build/gcc/src/gcc/libstdc++-v3/libsupc++/guard.cc:302
#2  0x00007ffff7b7a7cd in ?? () from /usr/lib/libQt5Network.so.5
#3  0x00007ffff7b7f286 in ?? () from /usr/lib/libQt5Network.so.5
#4  0x00007ffff7b96cfc in ?? () from /usr/lib/libQt5Network.so.5
#5  0x00007ffff7b9e0e2 in ?? () from /usr/lib/libQt5Network.so.5
#6  0x00007ffff7b6514b in QSslCertificate::QSslCertificate(QByteArray const&, QSsl::EncodingFormat) () from /usr/lib/libQt5Network.so.5
#7  0x00007ffff7b7ba52 in ?? () from /usr/lib/libQt5Network.so.5
#8  0x00007ffff7b6e75e in QSslConfiguration::defaultConfiguration() () from /usr/lib/libQt5Network.so.5
#9  0x00005555555d5d67 in main (argc=1, argv=0x7fffffffe568) at qt/bitcoin.cpp:565
```
So thanks the `#9` line, it became clear that Bitcoin is also affected by exactly the same issue in the same part of code:
https://bbs.archlinux.org/viewtopic.php?id=240553
https://bugs.archlinux.org/task/60235
https://github.com/bitcoin/bitcoin/issues/14273

Therefore, solution from https://github.com/bitcoin/bitcoin/issues/14273#issuecomment-424905851 is also valid for Emercoin. So I consider this Issue resolved. I will update PKGBUILD shortly.

> I also have some problems with installing Arch (never used it before), like ERROR: Failed to install packages to new root.

First of all, Arch is not attempts to be "user-friendly", so it's completely acceptable if you faced difficulty or just not understand something, at least until you not read (and share) the [Arch principles](https://wiki.archlinux.org/index.php/Arch_Linux#Principles) and, of course, [Installation guide](https://wiki.archlinux.org/index.php/Installation_guide), and some other articles from ArchWiki. Arch does not turn an easy things to elementary ones - but noticeable simplifies a difficult ones (e.g. compiling and packaging Emercoin).
