### ISSUE TITLE
What is the canonical spelling for Emercoin DNS feature?

### ISSUE THREAD

**Issue by lockedshadow** [emercoin/emercoin#87]
Judging by [documentation page](https://emercoin.com/en/documentation/blockchain-services/emerdns/emerdns-introduction), "Emer" + service abbreviation is a common spelling variant, but there also is a configuration option that named 'emcdns', that is a bit confusing. So should the "EmerDNS" be considered as canonical variant?

**Comment by mechnotech** [comment]
"emcdns" is the old name. We have come to call it "EmerDNS"
