### ISSUE TITLE
Can't download blockchain

### ISSUE THREAD

**Issue by bitcoren** [emercoin/emercoin#96]
Two days i can't download blockchain.
![1](https://user-images.githubusercontent.com/38252897/62186987-81786f80-b39a-11e9-8b35-4415dadd1f7c.png)
emercoin core 0.7.9 64bit, windows LTSC

**Comment by mechnotech** [comment]
Hi Bircoren! Please try this manual:
https://emercoin.com/en/news/chto-delat-esli-s-koshelkom-emercoin-chto-to-poshlo-ne-tak
